-- ============================================================
-- V1__create_core_tables.sql
-- ModelLite Repository - Core schema (10 tables)
-- H2 DDL (integration test environment)
--
-- Adapted from PostgreSQL version:
-- - Removed DEFAULT gen_random_uuid() (UUID generated by application)
-- - Removed partial unique constraint WHERE (deleted = FALSE) on model table
-- - Removed COMMENT ON TABLE/COLUMN (H2 does not support)
-- - Removed WHERE clause on indexes (H2 does not support partial indexes)
-- ============================================================

CREATE TABLE category (
    id                  UUID PRIMARY KEY,
    name                VARCHAR(100) NOT NULL UNIQUE,
    description         VARCHAR(500) DEFAULT '',
    is_builtin          BOOLEAN NOT NULL DEFAULT FALSE,
    create_time         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    update_time         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE model_type (
    id                  UUID PRIMARY KEY,
    category_id         UUID NOT NULL REFERENCES category(id),
    name                VARCHAR(100) NOT NULL,
    description         VARCHAR(500) DEFAULT '',
    is_builtin          BOOLEAN NOT NULL DEFAULT FALSE,
    create_time         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    update_time         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_model_type_name UNIQUE (category_id, name)
);

CREATE TABLE tag (
    id                  UUID PRIMARY KEY,
    name                VARCHAR(50) NOT NULL UNIQUE,
    tag_type            VARCHAR(20) NOT NULL,
    is_builtin          BOOLEAN NOT NULL DEFAULT FALSE,
    create_time         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    update_time         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE model (
    id                  UUID PRIMARY KEY,
    name                VARCHAR(255) NOT NULL,
    description         VARCHAR(2000) DEFAULT '',
    category_id         UUID NOT NULL REFERENCES category(id),
    type_id             UUID NOT NULL REFERENCES model_type(id),
    resource_group      VARCHAR(100) NOT NULL,
    create_user         VARCHAR(100) NOT NULL,
    author              VARCHAR(100) DEFAULT NULL,
    series_name         VARCHAR(255) DEFAULT NULL,
    model_size          BIGINT DEFAULT NULL,
    max_seq_length      INTEGER DEFAULT NULL,
    deleted             BOOLEAN NOT NULL DEFAULT FALSE,
    create_time         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    update_time         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_model_name UNIQUE (name, category_id, type_id)
);

CREATE TABLE model_version (
    id                  UUID PRIMARY KEY,
    model_id            UUID NOT NULL REFERENCES model(id),
    version_number      INTEGER NOT NULL,
    pvc_name            VARCHAR(255) DEFAULT NULL,
    internal_path       VARCHAR(1024) DEFAULT NULL,
    source_type         VARCHAR(20) DEFAULT NULL,
    nfs_server          VARCHAR(255) DEFAULT NULL,
    nfs_path            VARCHAR(1024) DEFAULT NULL,
    weight_type         VARCHAR(50) DEFAULT NULL,
    is_registered       BOOLEAN NOT NULL DEFAULT FALSE,
    status              VARCHAR(30) NOT NULL DEFAULT 'NoWeight',
    is_locked           BOOLEAN NOT NULL DEFAULT FALSE,
    train_frame         VARCHAR(100) DEFAULT NULL,
    train_type          VARCHAR(100) DEFAULT NULL,
    train_strategy      VARCHAR(100) DEFAULT NULL,
    train_time          BIGINT DEFAULT NULL,
    final_loss          VARCHAR(100) DEFAULT NULL,
    source_version      VARCHAR(50) DEFAULT NULL,
    deleted             BOOLEAN NOT NULL DEFAULT FALSE,
    create_time         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    update_time         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_model_version UNIQUE (model_id, version_number)
);

CREATE TABLE model_tag (
    id                  UUID PRIMARY KEY,
    model_id            UUID NOT NULL REFERENCES model(id),
    tag_id              UUID NOT NULL REFERENCES tag(id),
    create_time         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_model_tag UNIQUE (model_id, tag_id)
);

CREATE TABLE model_type_tag (
    id                  UUID PRIMARY KEY,
    type_id             UUID NOT NULL REFERENCES model_type(id),
    tag_id              UUID NOT NULL REFERENCES tag(id),
    create_time         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_model_type_tag UNIQUE (type_id, tag_id)
);

CREATE TABLE version_lock (
    id                  UUID PRIMARY KEY,
    version_id          UUID NOT NULL REFERENCES model_version(id),
    locker_id           VARCHAR(200) NOT NULL,
    lock_type           VARCHAR(30) NOT NULL,
    expire_time         TIMESTAMP WITH TIME ZONE NOT NULL,
    create_time         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE upload_task (
    id                  UUID PRIMARY KEY,
    model_id            UUID NOT NULL REFERENCES model(id),
    version_id          UUID NOT NULL REFERENCES model_version(id),
    source_type         VARCHAR(20) NOT NULL,
    source_path         VARCHAR(1024) NOT NULL,
    cifs_username       VARCHAR(200) DEFAULT NULL,
    cifs_password       VARCHAR(200) DEFAULT NULL,
    target_path         VARCHAR(1024) NOT NULL,
    progress            INTEGER DEFAULT 0,
    status              VARCHAR(20) NOT NULL DEFAULT 'Pending',
    error_message       VARCHAR(2000) DEFAULT NULL,
    create_user         VARCHAR(100) NOT NULL,
    deleted             BOOLEAN NOT NULL DEFAULT FALSE,
    create_time         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    update_time         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    version             BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_upload_version ON upload_task (version);

CREATE TABLE convert_task (
    id                  UUID PRIMARY KEY,
    model_id            UUID NOT NULL REFERENCES model(id),
    source_version_id   UUID NOT NULL REFERENCES model_version(id),
    target_version_id   UUID DEFAULT NULL REFERENCES model_version(id),
    source_format       VARCHAR(50) NOT NULL,
    target_format       VARCHAR(50) NOT NULL,
    progress            INTEGER DEFAULT 0,
    status              VARCHAR(20) NOT NULL DEFAULT 'Pending',
    error_message       VARCHAR(2000) DEFAULT NULL,
    create_user         VARCHAR(100) NOT NULL,
    deleted             BOOLEAN NOT NULL DEFAULT FALSE,
    create_time         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    update_time         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_model_category ON model (category_id);
CREATE INDEX idx_model_type ON model (type_id);
CREATE INDEX idx_model_resource_group ON model (resource_group);
CREATE INDEX idx_model_create_time ON model (create_time);

CREATE INDEX idx_version_model ON model_version (model_id);
CREATE INDEX idx_version_status ON model_version (status);

CREATE INDEX idx_lock_version ON version_lock (version_id);
CREATE INDEX idx_lock_expire ON version_lock (expire_time);
CREATE INDEX idx_lock_locker ON version_lock (locker_id, lock_type);

CREATE INDEX idx_upload_model ON upload_task (model_id);
CREATE INDEX idx_upload_status ON upload_task (status);

CREATE INDEX idx_convert_model ON convert_task (model_id);
CREATE INDEX idx_convert_status ON convert_task (status);

CREATE INDEX idx_tag_type ON tag (tag_type);

CREATE INDEX idx_model_tag_tag ON model_tag (tag_id);
CREATE INDEX idx_model_type_tag_tag ON model_type_tag (tag_id);
