apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "model-lite-repository.fullname" . }}-config
  labels:
    {{- include "model-lite-repository.labels" . | nindent 4 }}
data:
  application-k8s.yaml: |
    spring:
      datasource:
        hikari:
          maximum-pool-size: 10
          minimum-idle: 2
          connection-timeout: 30000
      jackson:
        serialization:
          write-dates-as-timestamps: false
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
      endpoint:
        health:
          probes:
            enabled: true
