{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "model-lite-repository.fullname" . }}-db
  labels:
    {{- include "model-lite-repository.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.database.username | b64enc | quote }}
  password: {{ .Values.database.password | b64enc | quote }}
{{- end }}
